version: '3'
services:

  # ClickHouse : 8123 # none / none
  # TABiX for ClickHouse client: http://localhost:8080
  # MariaDB CS : 3306
  # MariaDB    : 3307 # root/password
  # PostgreSQL : 5432 # postgres/password

  # client:
  #   image: yandex/clickhouse-client
  #   build: docker/client
  #   command: ['--host', 'server']
  clickhouse-server:
    image: yandex/clickhouse-server:18.10
    ports:
      - 8123:8123
      - 9000:9000
      - 9009:9009
    volumes:
      - ./volume/clickhouse:/var/lib/clickhouse

  clickhouse-tabix:
    image: spoonest/clickhouse-tabix-web-client:stable
    ports:
      - 8080:80
    environment:
      CH_HOST: clickhouse-server:8123

  # mariadb-columnstore:
  #   image: mariadb/columnstore_singlenode:1.1.5
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./volume/mariadb-cs/etc:/usr/local/mariadb/columnstore/etc
  #     - ./volume/mariadb-cs/data1:/usr/local/mariadb/columnstore/data1
  #     - ./volume/mariadb-cs/local:/usr/local/mariadb/columnstore/local
  #     - ./volume/mariadb-cs/db:/usr/local/mariadb/columnstore/mysql/db
  #   environment:
  #     CS_DATABASE: db_bench

  mariadb-standard:
    image: mariadb:10.3.8
    volumes:
      - ./volume/mariadb-standard/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3307:3306"

  postgresql:
    image: postgres:10.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./volume/postgresql/data:/var/lib/postgresql/data
